### ISSUE TITLE
use svidget inside svg

### ISSUE THREAD

**Issue by zatalian** [joeax/svidget#2]
Is it possible to use svidget's inside a svg document instead of a html document?
If I import the spinningStar example as an object in a bigger svg document, I get an iframe "spinningStar_frame" if I inspect the result, but no stars to be seen...

**Comment by joeax** [comment]
I never intended to support embedding a svidget inside another SVG document (or another svidget). It's on the roadmap to make html widgetable however so you can achieve nesting that way. 

However I'm intrigued how you are getting an iframe. Can you provide the code you are using to embed the svidget so I can investigate further?

**Comment by zatalian** [comment]
I seem to have hit a surprisingly hard problem... or i am looking in the
wrong direction...
I'm trying to create some sort of HMI
https://www.google.be/search?q=hmi&tbm=isch&tbo=u&source=univ&sa=X&ei=f7mHVafRLsS1UZmFgcAM&ved=0CD4QsAQ&biw=1920&bih=943,
and i need some symbols (tanks, valves, pumps, ...) that can be altered
with parameters (level of the tanks, position of the valves, ...) . Svg
symbols in a bigger svg is a must because i need exact positions, scaling,
...

the possibility to work with "symbol" in svg is exactly what i need if
parameters would be supported as proposed here
http://www.w3.org/TR/SVGParamPrimer/.

Anyway, attached you'll find the code that generates an iframe if you
inspect the page with firefox. The page is called index2.html and inside is
an object "SpinningStar".

**Comment by joeax** [comment]
Can you send the code to my email directly joeagster@outlook.com. 

Svidget is based on SVGParam spec, but the `<object>` tag must be in HTML (see that page section 2.1). But you can precisely position and scale the `object` elements in HTML.

To position, add CSS positioning via `style` attribute:
`<object id="spinningStar" role="svidget" data="spinningStar.svg" type="image/svg+xml" width="400" height="400" style="position: absolute; left: 150px; top: 200px;">`

To scale, just ensure your SVG has a viewBox attribute. Here is an example from the spinning star:
`<svg width="200" height="200" viewBox="0 0 200 200">`
Then, change the `<object width="50" height="50>` width and height to whatever you want.

HMI was one of the inspirations for creating this framework. The HTML page is essentially your HMI drawing and the SVG svidgets are your symbols. Similar to a symbol, the svidget is its own autonomous artifact complete with its own DOM structure, scripts and CSS.

**Comment by joeax** [comment]
Update. You can wrap an `<object>` in an `<foreignObject>`, however this works in chrome and Firefox but not IE. IE has never really supported the `<foreignObject>` tag. As far as loading in an iframe, this is because the browser is giving an access denied when trying to access the DOM of the `<object>` tag. When svidget detects cross site loading it switches to an `<iframe>`.

I did fix a couple issues I found with the display of iframes notably the frame borders and the fact that it wasn't scaling the SVG property. Version 0.3.1 addresses these issues.

**Comment by joeax** [comment]
I posted a new demo to svidget.com showing loading multiple stars at arbitrary positoins:
http://www.svidget.com/labs/starrynight

I'm pushing 0.3.3 shortly which further simplifies positioning. Good luck with whatever you decide to do. Closing issue.

**Comment by Kortenbach** [comment]
I stumbled upon this issue-post just now. I want to do exactly the same thing as zatalian i.e. embed a svidget inside an svg for use as an HMI. Inkscape utilizes the <use > tag to refer to symbols (containing svidgets). It might be possible to swap the use tags with foreignobject tags... However, it would be awesome if it would work out of the box since the use tag has a lot of issues with virtual DOM stuff etc which is way over my head...

I wouldn't go for positioning the svg objects in html since they would have to be connected with pipes etc as is customary with HMI screens.

@zatalian: how did this end for you?
